{
  "uid" : "99a22866d8d7106e",
  "name" : "test_t_case001",
  "fullName" : "test_proj.test_index_0#test_t_case001",
  "historyId" : "c20f4104b80c968b53dea94058396756",
  "time" : {
    "start" : 1626893971145,
    "stop" : 1626893979498,
    "duration" : 8353
  },
  "status" : "broken",
  "statusMessage" : "FileNotFoundError: [Errno 2] No such file or directory: 'data/a001.csv'",
  "statusTrace" : "def test_t_case001():\n>       import test_tcA001 as tc01\n\ntest_proj/test_index_0.py:29: \n_ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ \n<frozen importlib._bootstrap>:1007: in _find_and_load\n    ???\n<frozen importlib._bootstrap>:986: in _find_and_load_unlocked\n    ???\n<frozen importlib._bootstrap>:680: in _load_unlocked\n    ???\n/opt/hostedtoolcache/Python/3.9.5/x64/lib/python3.9/site-packages/_pytest/assertion/rewrite.py:170: in exec_module\n    exec(co, module.__dict__)\ntest_proj/test_tcA001.py:39: in <module>\n    list_user = test_A001_users()\n_ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ \n\n    def test_A001_users():\n        filename = \"data/a001.csv\"\n>       with open(filename, \"r\", encoding='utf-8') as csvfile:\nE       FileNotFoundError: [Errno 2] No such file or directory: 'data/a001.csv'\n\ntest_proj/test_tcA001.py:31: FileNotFoundError",
  "flaky" : false,
  "newFailed" : false,
  "beforeStages" : [ ],
  "testStage" : {
    "status" : "broken",
    "statusMessage" : "FileNotFoundError: [Errno 2] No such file or directory: 'data/a001.csv'",
    "statusTrace" : "def test_t_case001():\n>       import test_tcA001 as tc01\n\ntest_proj/test_index_0.py:29: \n_ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ \n<frozen importlib._bootstrap>:1007: in _find_and_load\n    ???\n<frozen importlib._bootstrap>:986: in _find_and_load_unlocked\n    ???\n<frozen importlib._bootstrap>:680: in _load_unlocked\n    ???\n/opt/hostedtoolcache/Python/3.9.5/x64/lib/python3.9/site-packages/_pytest/assertion/rewrite.py:170: in exec_module\n    exec(co, module.__dict__)\ntest_proj/test_tcA001.py:39: in <module>\n    list_user = test_A001_users()\n_ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ \n\n    def test_A001_users():\n        filename = \"data/a001.csv\"\n>       with open(filename, \"r\", encoding='utf-8') as csvfile:\nE       FileNotFoundError: [Errno 2] No such file or directory: 'data/a001.csv'\n\ntest_proj/test_tcA001.py:31: FileNotFoundError",
    "steps" : [ ],
    "attachments" : [ {
      "uid" : "ebae1a7dba49fef2",
      "name" : "log",
      "source" : "ebae1a7dba49fef2.txt",
      "type" : "text/plain",
      "size" : 642
    }, {
      "uid" : "679accd2173ea55d",
      "name" : "stderr",
      "source" : "679accd2173ea55d.txt",
      "type" : "text/plain",
      "size" : 435
    } ],
    "parameters" : [ ],
    "stepsCount" : 0,
    "attachmentsCount" : 2,
    "shouldDisplayMessage" : true,
    "hasContent" : true
  },
  "afterStages" : [ ],
  "labels" : [ {
    "name" : "parentSuite",
    "value" : "test_proj"
  }, {
    "name" : "suite",
    "value" : "test_index_0"
  }, {
    "name" : "host",
    "value" : "fv-az83-172"
  }, {
    "name" : "thread",
    "value" : "4095-MainThread"
  }, {
    "name" : "framework",
    "value" : "pytest"
  }, {
    "name" : "language",
    "value" : "cpython3"
  }, {
    "name" : "package",
    "value" : "test_proj.test_index_0"
  }, {
    "name" : "resultFormat",
    "value" : "allure2"
  } ],
  "parameters" : [ ],
  "links" : [ ],
  "hidden" : false,
  "retry" : false,
  "extra" : {
    "severity" : "normal",
    "retries" : [ ],
    "categories" : [ {
      "name" : "Test defects",
      "matchedStatuses" : [ ],
      "flaky" : false
    } ],
    "tags" : [ ]
  },
  "source" : "99a22866d8d7106e.json",
  "parameterValues" : [ ]
}